DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS site_category CASCADE;
DROP TABLE IF EXISTS site CASCADE;
DROP TABLE IF EXISTS team CASCADE;
DROP TABLE IF EXISTS sales CASCADE;